### ISSUE TITLE
Unable to initialize classification algorithm on master

### ISSUE THREAD

**Issue by Rubenkl** [comic/evalutils#293]
* evalutils version: 0.2.2
* Python version: 3.7.5
* Operating System: Windows 10 64-bit

### Description

Unable to initialize _algorithm_ cookiecutter? (_evaluation_ does work fine)

### What I Did

After installing using pip+git (provided by James) using:
`pip install git+https://github.com/comic/evalutils.git`

Followed console output after `evalutils init algorithm myalgorithm
```
What kind of algorithm is this? [Classification|Segmentation|Detection] (Classification, Segmentation, Detection): Classification
Required number of cpus? [1]: 2
Required node capability? (e.g.: avx) *()* []:
Are *()* all required node capabilities? [Y/n]: Y
Minimal required amount of cpu RAM? [1G]: 16G
Required number of gpus? [0]: 1
Required gpu compute capability (version string e.g.: 1.5.0) []:
Required gpu memory? (e.g.: 4G) []: 10G
Traceback (most recent call last):
  File "C:\Users\Ruben\AppData\Local\Temp\tmp0xbo9s69.py", line 30, in <module>
    str(expected_output_file), template_dir / "test" / "expected_output.json"
  File "c:\users\ruben\appdata\local\programs\python\python37\lib\shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "c:\users\ruben\appdata\local\programs\python\python37\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\ruben\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\tests\\resources\\json\\results_classification.json'
Stopping generation because post_gen_project hook script didn't exit successfully
```

**Comment by Rubenkl** [comment]
@silvandeleemput

**Comment by silvandeleemput** [comment]
@Rubenkl A new version of evalutils (v0.2.3) has been released with the fix. Using this version you should be able to initialize an algorithm template now.
